-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 18:45:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema otter_worlds
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `otter_worlds` ;

-- -----------------------------------------------------
-- Schema otter_worlds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `otter_worlds` DEFAULT CHARACTER SET utf8 ;
USE `otter_worlds` ;

-- -----------------------------------------------------
-- Table `otter_worlds`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`universe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`universe` (
  `idUniverse` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `bIsPublic` TINYINT NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idUniverse`),
  INDEX `fk_univers_utilisateur_idx` (`user_idUser` ASC) VISIBLE,
  UNIQUE INDEX `un_idOwner_name` (`user_idUser` ASC, `name` ASC) VISIBLE,
  CONSTRAINT `fk_univers_utilisateur`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `otter_worlds`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`topic` (
  `idTopic` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `order` INT NULL,
  `universe_idUniverse` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`idTopic`),
  INDEX `fk_topic_universe1_idx` (`universe_idUniverse` ASC) VISIBLE,
  INDEX `fk_topic_article1_idx` (`article_idArticle` ASC) VISIBLE,
  UNIQUE INDEX `un_name_univers` (`name` ASC, `universe_idUniverse` ASC) VISIBLE,
  UNIQUE INDEX `un_order_univers` (`order` ASC, `universe_idUniverse` ASC) VISIBLE,
  CONSTRAINT `fk_topic_universe1`
    FOREIGN KEY (`universe_idUniverse`)
    REFERENCES `otter_worlds`.`universe` (`idUniverse`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topic_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `otter_worlds`.`article` (`idArticle`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`subTopic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`subTopic` (
  `idSubTopic` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `order` INT NULL,
  `topic_idTopic` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`idSubTopic`),
  INDEX `fk_subTopic_topic1_idx` (`topic_idTopic` ASC) VISIBLE,
  INDEX `fk_subTopic_article1_idx` (`article_idArticle` ASC) VISIBLE,
  UNIQUE INDEX `un_name_topic` (`name` ASC, `topic_idTopic` ASC) VISIBLE,
  UNIQUE INDEX `un_oreder_topic` (`order` ASC, `topic_idTopic` ASC) VISIBLE,
  CONSTRAINT `fk_subTopic_topic1`
    FOREIGN KEY (`topic_idTopic`)
    REFERENCES `otter_worlds`.`topic` (`idTopic`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subTopic_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `otter_worlds`.`article` (`idArticle`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`article` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `content` LONGTEXT NULL,
  `thumbnail` VARCHAR(1024) NULL,
  `subTopic_idSubTopic` INT NOT NULL,
  PRIMARY KEY (`idArticle`),
  INDEX `fk_article_subTopic1_idx` (`subTopic_idSubTopic` ASC) VISIBLE,
  UNIQUE INDEX `un_title_subTopic` (`title` ASC, `subTopic_idSubTopic` ASC) VISIBLE,
  CONSTRAINT `fk_article_subTopic1`
    FOREIGN KEY (`subTopic_idSubTopic`)
    REFERENCES `otter_worlds`.`subTopic` (`idSubTopic`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`map` (
  `idMap` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `extension` VARCHAR(5) NULL,
  `universe_idUniverse` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`idMap`),
  INDEX `fk_maps_univers1_idx` (`universe_idUniverse` ASC) VISIBLE,
  UNIQUE INDEX `un_universe_name` (`universe_idUniverse` ASC, `name` ASC) VISIBLE,
  INDEX `fk_map_article1_idx` (`article_idArticle` ASC) VISIBLE,
  CONSTRAINT `fk_maps_univers1`
    FOREIGN KEY (`universe_idUniverse`)
    REFERENCES `otter_worlds`.`universe` (`idUniverse`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_map_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `otter_worlds`.`article` (`idArticle`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`interestPoint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`interestPoint` (
  `id_interestPoint` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `coordinate` VARCHAR(45) NOT NULL,
  `map_idMap` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`id_interestPoint`),
  INDEX `fk_interestPoint_maps1_idx` (`map_idMap` ASC) VISIBLE,
  INDEX `fk_interestPoint_article1_idx` (`article_idArticle` ASC) VISIBLE,
  UNIQUE INDEX `un_coordinate_map` (`coordinate` ASC, `map_idMap` ASC) VISIBLE,
  CONSTRAINT `fk_interestPoint_maps1`
    FOREIGN KEY (`map_idMap`)
    REFERENCES `otter_worlds`.`map` (`idMap`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interestPoint_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `otter_worlds`.`article` (`idArticle`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`character` (
  `idCharacter` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `backstory` TEXT NULL,
  `user_idUser` INT NOT NULL,
  `universe_idUniverse` INT NOT NULL,
  PRIMARY KEY (`idCharacter`),
  INDEX `fk_characters_users1_idx` (`user_idUser` ASC) VISIBLE,
  INDEX `fk_characters_univers1_idx` (`universe_idUniverse` ASC) VISIBLE,
  UNIQUE INDEX `un_name_universe` (`name` ASC, `universe_idUniverse` ASC) VISIBLE,
  CONSTRAINT `fk_characters_users1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `otter_worlds`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_characters_univers1`
    FOREIGN KEY (`universe_idUniverse`)
    REFERENCES `otter_worlds`.`universe` (`idUniverse`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`templateCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`templateCategory` (
  `idTemplateCategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `order` INT NULL,
  `universe_idUniverse` INT NOT NULL,
  PRIMARY KEY (`idTemplateCategory`),
  INDEX `fk_templateCategory_universe1_idx` (`universe_idUniverse` ASC) VISIBLE,
  UNIQUE INDEX `un_universe_order` (`order` ASC, `universe_idUniverse` ASC) VISIBLE,
  UNIQUE INDEX `un_universe_name` (`name` ASC, `universe_idUniverse` ASC) VISIBLE,
  CONSTRAINT `fk_templateCategory_universe1`
    FOREIGN KEY (`universe_idUniverse`)
    REFERENCES `otter_worlds`.`universe` (`idUniverse`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`templateStat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`templateStat` (
  `idTemplateStat` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `bIsNumber` TINYINT NULL,
  `bIsRequired` TINYINT NULL,
  `templateCategory_idTemplateCategory` INT NOT NULL,
  PRIMARY KEY (`idTemplateStat`),
  INDEX `fk_templateStat_templateCategory1_idx` (`templateCategory_idTemplateCategory` ASC) VISIBLE,
  UNIQUE INDEX `un_name_idCategory` (`name` ASC, `templateCategory_idTemplateCategory` ASC) VISIBLE,
  CONSTRAINT `fk_templateStat_templateCategory1`
    FOREIGN KEY (`templateCategory_idTemplateCategory`)
    REFERENCES `otter_worlds`.`templateCategory` (`idTemplateCategory`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`stat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`stat` (
  `value` VARCHAR(45) NULL DEFAULT 0,
  `character_idCharacter` INT NOT NULL,
  `templateStat_idTemplateStat` INT NOT NULL,
  INDEX `fk_stats_characters1_idx` (`character_idCharacter` ASC) VISIBLE,
  INDEX `fk_stat_templateStat1_idx` (`templateStat_idTemplateStat` ASC) VISIBLE,
  UNIQUE INDEX `un_character_templateStat` (`character_idCharacter` ASC, `templateStat_idTemplateStat` ASC) VISIBLE,
  CONSTRAINT `fk_stats_characters1`
    FOREIGN KEY (`character_idCharacter`)
    REFERENCES `otter_worlds`.`character` (`idCharacter`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stat_templateStat1`
    FOREIGN KEY (`templateStat_idTemplateStat`)
    REFERENCES `otter_worlds`.`templateStat` (`idTemplateStat`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`inventory` (
  `idInventory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `number` INT NULL,
  `description` TEXT NOT NULL,
  `weight` INT NULL,
  `character_idCharacter` INT NOT NULL,
  PRIMARY KEY (`idInventory`),
  INDEX `fk_inventaire_characters1_idx` (`character_idCharacter` ASC) VISIBLE,
  UNIQUE INDEX `un_name_character` (`name` ASC, `character_idCharacter` ASC) VISIBLE,
  CONSTRAINT `fk_inventaire_characters1`
    FOREIGN KEY (`character_idCharacter`)
    REFERENCES `otter_worlds`.`character` (`idCharacter`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`keyword` (
  `idKeyword` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idKeyword`),
  UNIQUE INDEX `un_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`keywordArticle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`keywordArticle` (
  `keywords_idKeyword` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`keywords_idKeyword`, `article_idArticle`),
  INDEX `fk_keyWords_has_article_article1_idx` (`article_idArticle` ASC) VISIBLE,
  INDEX `fk_keyWords_has_article_keyWords1_idx` (`keywords_idKeyword` ASC) VISIBLE,
  UNIQUE INDEX `un_keyword_article` (`keywords_idKeyword` ASC, `article_idArticle` ASC) VISIBLE,
  CONSTRAINT `fk_keyWords_has_article_keyWords1`
    FOREIGN KEY (`keywords_idKeyword`)
    REFERENCES `otter_worlds`.`keyword` (`idKeyword`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_keyWords_has_article_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `otter_worlds`.`article` (`idArticle`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`timeline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`timeline` (
  `idTimeline` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TINYTEXT NULL,
  `universe_idUniverse` INT NOT NULL,
  PRIMARY KEY (`idTimeline`),
  INDEX `fk_timeline_universe1_idx` (`universe_idUniverse` ASC) VISIBLE,
  UNIQUE INDEX `un_name_universe` (`name` ASC, `universe_idUniverse` ASC) VISIBLE,
  CONSTRAINT `fk_timeline_universe1`
    FOREIGN KEY (`universe_idUniverse`)
    REFERENCES `otter_worlds`.`universe` (`idUniverse`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otter_worlds`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otter_worlds`.`event` (
  `idEvent` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `timeline_idTimeline` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`idEvent`),
  INDEX `fk_event_timeline1_idx` (`timeline_idTimeline` ASC) VISIBLE,
  INDEX `fk_event_article1_idx` (`article_idArticle` ASC) VISIBLE,
  UNIQUE INDEX `un_name_timeline` (`name` ASC, `timeline_idTimeline` ASC) VISIBLE,
  CONSTRAINT `fk_event_timeline1`
    FOREIGN KEY (`timeline_idTimeline`)
    REFERENCES `otter_worlds`.`timeline` (`idTimeline`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `otter_worlds`.`article` (`idArticle`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
