-- MySQL Script generated by MySQL Workbench
-- Sun Nov  8 18:24:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Otter_World
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Otter_World
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Otter_World` DEFAULT CHARACTER SET utf8 ;
USE `Otter_World` ;

-- -----------------------------------------------------
-- Table `Otter_World`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`user` (
  `idUser` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`universe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`universe` (
  `idUniverse` INT NOT NULL AUTO_INCREMENT,
  `public` TINYINT NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `id_owner` INT NOT NULL,
  PRIMARY KEY (`idUniverse`),
  INDEX `fk_univers_utilisateur_idx` (`id_owner` ASC) VISIBLE,
  UNIQUE INDEX `un_idOwner_name` (`id_owner` ASC, `name` ASC) VISIBLE,
  CONSTRAINT `fk_univers_utilisateur`
    FOREIGN KEY (`id_owner`)
    REFERENCES `Otter_World`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`topic` (
  `idTopic` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `order` INT NULL,
  `universe_idUniverse` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`idTopic`),
  INDEX `fk_topic_universe1_idx` (`universe_idUniverse` ASC) VISIBLE,
  INDEX `fk_topic_article1_idx` (`article_idArticle` ASC) VISIBLE,
  UNIQUE INDEX `un_name_univers` (`name` ASC, `universe_idUniverse` ASC) VISIBLE,
  UNIQUE INDEX `un_order_univers` (`order` ASC, `universe_idUniverse` ASC) VISIBLE,
  CONSTRAINT `fk_topic_universe1`
    FOREIGN KEY (`universe_idUniverse`)
    REFERENCES `Otter_World`.`universe` (`idUniverse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topic_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `Otter_World`.`article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`subTopic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`subTopic` (
  `idSubTopic` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `order` INT NULL,
  `topic_idTopic` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`idSubTopic`),
  INDEX `fk_subTopic_topic1_idx` (`topic_idTopic` ASC) VISIBLE,
  INDEX `fk_subTopic_article1_idx` (`article_idArticle` ASC) VISIBLE,
  UNIQUE INDEX `un_name_topic` (`name` ASC, `topic_idTopic` ASC) VISIBLE,
  UNIQUE INDEX `un_oreder_topic` (`order` ASC, `topic_idTopic` ASC) VISIBLE,
  CONSTRAINT `fk_subTopic_topic1`
    FOREIGN KEY (`topic_idTopic`)
    REFERENCES `Otter_World`.`topic` (`idTopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subTopic_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `Otter_World`.`article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`article` (
  `idArticle` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` LONGTEXT NULL,
  `thumbnail` VARCHAR(1024) NULL,
  `subTopic_idSubTopic` INT NOT NULL,
  PRIMARY KEY (`idArticle`),
  INDEX `fk_article_subTopic1_idx` (`subTopic_idSubTopic` ASC) VISIBLE,
  UNIQUE INDEX `un_title_subTopic` (`title` ASC, `subTopic_idSubTopic` ASC) VISIBLE,
  CONSTRAINT `fk_article_subTopic1`
    FOREIGN KEY (`subTopic_idSubTopic`)
    REFERENCES `Otter_World`.`subTopic` (`idSubTopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`map` (
  `idMap` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `extension` VARCHAR(5) NULL,
  `universe_idUniverse` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`idMap`),
  INDEX `fk_maps_univers1_idx` (`universe_idUniverse` ASC) VISIBLE,
  UNIQUE INDEX `un_universe_name` (`universe_idUniverse` ASC, `name` ASC) VISIBLE,
  INDEX `fk_map_article1_idx` (`article_idArticle` ASC) VISIBLE,
  CONSTRAINT `fk_maps_univers1`
    FOREIGN KEY (`universe_idUniverse`)
    REFERENCES `Otter_World`.`universe` (`idUniverse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_map_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `Otter_World`.`article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`interestPoint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`interestPoint` (
  `id_interestPoint` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `coordinate` VARCHAR(45) NOT NULL,
  `id_map` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`id_interestPoint`),
  INDEX `fk_interestPoint_maps1_idx` (`id_map` ASC) VISIBLE,
  INDEX `fk_interestPoint_article1_idx` (`article_idArticle` ASC) VISIBLE,
  UNIQUE INDEX `un_coordinate_map` (`coordinate` ASC, `id_map` ASC) VISIBLE,
  CONSTRAINT `fk_interestPoint_maps1`
    FOREIGN KEY (`id_map`)
    REFERENCES `Otter_World`.`map` (`idMap`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interestPoint_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `Otter_World`.`article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`character` (
  `idCharacter` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `backstory` TEXT NULL,
  `users_idUser` INT NOT NULL,
  `univers_idUniverse` INT NOT NULL,
  PRIMARY KEY (`idCharacter`),
  INDEX `fk_characters_users1_idx` (`users_idUser` ASC) VISIBLE,
  INDEX `fk_characters_univers1_idx` (`univers_idUniverse` ASC) VISIBLE,
  UNIQUE INDEX `un_name_universe` (`name` ASC, `univers_idUniverse` ASC) VISIBLE,
  CONSTRAINT `fk_characters_users1`
    FOREIGN KEY (`users_idUser`)
    REFERENCES `Otter_World`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_characters_univers1`
    FOREIGN KEY (`univers_idUniverse`)
    REFERENCES `Otter_World`.`universe` (`idUniverse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`templateCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`templateCategory` (
  `idTemplateCategory` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `order` INT NULL,
  `universe_idUniverse` INT NOT NULL,
  PRIMARY KEY (`idTemplateCategory`),
  INDEX `fk_templateCategory_universe1_idx` (`universe_idUniverse` ASC) VISIBLE,
  UNIQUE INDEX `un_universe_order` (`order` ASC, `universe_idUniverse` ASC) VISIBLE,
  UNIQUE INDEX `un_universe_name` (`name` ASC, `universe_idUniverse` ASC) VISIBLE,
  CONSTRAINT `fk_templateCategory_universe1`
    FOREIGN KEY (`universe_idUniverse`)
    REFERENCES `Otter_World`.`universe` (`idUniverse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`templateStat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`templateStat` (
  `idTemplateStat` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `isNumber` TINYINT NULL,
  `required` TINYINT NULL,
  `templateCategory_idTemplateCategory` INT NOT NULL,
  PRIMARY KEY (`idTemplateStat`),
  INDEX `fk_templateStat_templateCategory1_idx` (`templateCategory_idTemplateCategory` ASC) VISIBLE,
  UNIQUE INDEX `un_name_idCategory` (`name` ASC, `templateCategory_idTemplateCategory` ASC) VISIBLE,
  CONSTRAINT `fk_templateStat_templateCategory1`
    FOREIGN KEY (`templateCategory_idTemplateCategory`)
    REFERENCES `Otter_World`.`templateCategory` (`idTemplateCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`stat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`stat` (
  `value` VARCHAR(45) NULL DEFAULT 0,
  `characters_idCharacter` INT NOT NULL,
  `templateStat_idTemplateStat` INT NOT NULL,
  INDEX `fk_stats_characters1_idx` (`characters_idCharacter` ASC) VISIBLE,
  INDEX `fk_stat_templateStat1_idx` (`templateStat_idTemplateStat` ASC) VISIBLE,
  UNIQUE INDEX `un_character_templateStat` (`characters_idCharacter` ASC, `templateStat_idTemplateStat` ASC) VISIBLE,
  CONSTRAINT `fk_stats_characters1`
    FOREIGN KEY (`characters_idCharacter`)
    REFERENCES `Otter_World`.`character` (`idCharacter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stat_templateStat1`
    FOREIGN KEY (`templateStat_idTemplateStat`)
    REFERENCES `Otter_World`.`templateStat` (`idTemplateStat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`inventory` (
  `idInventory` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `number` INT NULL,
  `description` TEXT NOT NULL,
  `weight` INT NULL,
  `character_idCharacter` INT NOT NULL,
  PRIMARY KEY (`idInventory`),
  INDEX `fk_inventaire_characters1_idx` (`character_idCharacter` ASC) VISIBLE,
  UNIQUE INDEX `un_name_character` (`name` ASC, `character_idCharacter` ASC) VISIBLE,
  CONSTRAINT `fk_inventaire_characters1`
    FOREIGN KEY (`character_idCharacter`)
    REFERENCES `Otter_World`.`character` (`idCharacter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`keyword` (
  `idKeyword` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idKeyword`),
  UNIQUE INDEX `un_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`keywordArticle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`keywordArticle` (
  `keywords_idKeyword` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`keywords_idKeyword`, `article_idArticle`),
  INDEX `fk_keyWords_has_article_article1_idx` (`article_idArticle` ASC) VISIBLE,
  INDEX `fk_keyWords_has_article_keyWords1_idx` (`keywords_idKeyword` ASC) VISIBLE,
  UNIQUE INDEX `un_keyword_article` (`keywords_idKeyword` ASC, `article_idArticle` ASC) VISIBLE,
  CONSTRAINT `fk_keyWords_has_article_keyWords1`
    FOREIGN KEY (`keywords_idKeyword`)
    REFERENCES `Otter_World`.`keyword` (`idKeyword`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_keyWords_has_article_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `Otter_World`.`article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`timeline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`timeline` (
  `idTimeline` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` TINYTEXT NULL,
  `universe_idUniverse` INT NOT NULL,
  PRIMARY KEY (`idTimeline`),
  INDEX `fk_timeline_universe1_idx` (`universe_idUniverse` ASC) VISIBLE,
  UNIQUE INDEX `un_name_universe` (`name` ASC, `universe_idUniverse` ASC) VISIBLE,
  CONSTRAINT `fk_timeline_universe1`
    FOREIGN KEY (`universe_idUniverse`)
    REFERENCES `Otter_World`.`universe` (`idUniverse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Otter_World`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Otter_World`.`event` (
  `idEvent` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `timeline_idTimeline` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`idEvent`),
  INDEX `fk_event_timeline1_idx` (`timeline_idTimeline` ASC) VISIBLE,
  INDEX `fk_event_article1_idx` (`article_idArticle` ASC) VISIBLE,
  UNIQUE INDEX `un_name_timeline` (`name` ASC, `timeline_idTimeline` ASC) VISIBLE,
  CONSTRAINT `fk_event_timeline1`
    FOREIGN KEY (`timeline_idTimeline`)
    REFERENCES `Otter_World`.`timeline` (`idTimeline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `Otter_World`.`article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
